"""Stable, non-sensitive error codes returned to KuberPilot and operators."""

from enum import Enum


class ErrorCode(str, Enum):
    PLATFORM_NOT_FOUND = "PLATFORM_NOT_FOUND"
    PLATFORM_DISABLED = "PLATFORM_DISABLED"
    INVALID_TARGET = "INVALID_TARGET"
    TARGET_NOT_ALLOWED = "TARGET_NOT_ALLOWED"
    DNS_RESOLUTION_FAILED = "DNS_RESOLUTION_FAILED"
    TCP_CONNECTION_FAILED = "TCP_CONNECTION_FAILED"
    TCP_CONNECTION_REFUSED = "TCP_CONNECTION_REFUSED"
    TCP_TIMEOUT = "TCP_TIMEOUT"
    TLS_PRIVATE_CA_UNTRUSTED = "TLS_PRIVATE_CA_UNTRUSTED"
    TLS_CERTIFICATE_EXPIRED = "TLS_CERTIFICATE_EXPIRED"
    TLS_HOSTNAME_MISMATCH = "TLS_HOSTNAME_MISMATCH"
    TLS_HANDSHAKE_FAILED = "TLS_HANDSHAKE_FAILED"
    PROXY_CONNECTION_FAILED = "PROXY_CONNECTION_FAILED"
    HTTP_REQUEST_FAILED = "HTTP_REQUEST_FAILED"
    HTTP_REDIRECT_NOT_ALLOWED = "HTTP_REDIRECT_NOT_ALLOWED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
